// Planet
export const GET_PLANET_START = "GET_PLANET_START";
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS";
export const GET_PLANET_FAIL = "GET_PLANET_FAIL";
export const SET_PLANET = "SET_PLANET";